*---------------------------------------------------------------------*
*    program for:   TABLEFRAME_ZJMQM_QM009_Q
*   generated by table maintenance generator
*---------------------------------------------------------------------*
FUNCTION TABLEFRAME_ZJMQM_QM009_Q      .

  PERFORM TABLEFRAME TABLES X_HEADER X_NAMTAB DBA_SELLIST DPL_SELLIST
                            EXCL_CUA_FUNCT
                     USING  CORR_NUMBER VIEW_ACTION VIEW_NAME.

ENDFUNCTION.
