*---------------------------------------------------------------------*
*    view related PAI modules
*   generated by table maintenance generator
*---------------------------------------------------------------------*

INCLUDE LSVIMITX . "base table related PAI modules
