*---------------------------------------------------------------------*
*    view related data declarations
*   generated by table maintenance generator
*---------------------------------------------------------------------*
*...processing: ZJMQM_QM009_Q...................................*
DATA:  BEGIN OF STATUS_ZJMQM_QM009_Q                 .   "state vector
         INCLUDE STRUCTURE VIMSTATUS.
DATA:  END OF STATUS_ZJMQM_QM009_Q                 .
CONTROLS: TCTRL_ZJMQM_QM009_Q
            TYPE TABLEVIEW USING SCREEN '0200'.
*.........table declarations:.................................*
TABLES: *ZJMQM_QM009_Q                 .
TABLES: ZJMQM_QM009_Q                  .

* general table data declarations..............
  INCLUDE LSVIMTDT                                .
