*---------------------------------------------------------------------*
*    program for:   TABLEPROC_ZJMQM_QM009_Q
*   generated by table maintenance generator
*---------------------------------------------------------------------*
FUNCTION TABLEPROC_ZJMQM_QM009_Q       .

  PERFORM TABLEPROC.

ENDFUNCTION.
