*   generated by table maintenance generator
FUNCTION-POOL ZJMQM_QM009_Q              MESSAGE-ID SV.

* INCLUDE LZJMQM_QM009_QD...                 " Local class definition
  INCLUDE LSVIMDAT                                . "general data decl.
  INCLUDE LZJMQM_QM009_QT00                       . "view rel. data dcl.
