*---------------------------------------------------------------------*
*    view related FORM routines
*   generated by table maintenance generator
*---------------------------------------------------------------------*

* base table related FORM-routines.............
INCLUDE LSVIMFTX .
